apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  annotations:
    argocd.argoproj.io/sync-options: Replace=false
  name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}

